### PR TITLE
remarkable toolchain spec

### PR DESCRIPTION
**Pull request by tcrs**
Copied from Kobo, bumped kernel and glibc versions to those shipped on
Zero Gravitas. Changed CPU to cortex-a9.

### CODE REVIEW

**Comment by NiLuJe** [comment]
Do current FW versions actually now run a 4.9 kernel, or are they still using 4.1.18?

If it's still on 4.1, I'd update `CT_KERNEL_V_4_9=y` accordingly, to `CT_KERNEL_V_4_1=y`.

Keeping `CT_LIBC_GLIBC_MIN_KERNEL_VERSION="4.1.28"` sounds sensible no matter what, though ;).

**Comment by tcrs** [comment]
They are on 4.9 now:
```
remarkable: ~/ uname -a
Linux remarkable 4.9.84-zero-gravitas #1 Thu Oct 3 10:31:42 UTC 2019 armv7l GNU/Linux
```

**Comment by NiLuJe** [comment]
Cool, then this is good to go, thanks!

I'll merge this and update koxtoolchain as soon as I get back to a real
computer ;).

**Comment by NiLuJe** [comment]
Oops, just renamed it to add the "hf" suffix, because it's hard-float ;).

**Pull request merged**
